# .slather.yml

coverage_service: cobertura_xml
xcodeproj: ./SimpleLogger.xcodeproj
workspace: ./SimpleLogger.xcworkspace
scheme: SimpleLogger
source_directory: ./SimpleLoggerExample/*
output_directory: ./test-reports
ignore:
- "**/Pods/*"
- "**/SimpleLoggerTests/*"
