language: objective-c
osx_image: xcode11.6
xcode_project: SimpleLogger.xcodeproj
xcode_workspace: SimpleLogger.xcworkspace
xcode_scheme: SimpleLogger
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
