source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => 8.0
inhibit_all_warnings!
use_frameworks!

def shared_pods
    pod 'AWSS3'
end

target 'SimpleLogger' do
    shared_pods
end

target 'SimpleLoggerTests' do
    shared_pods
    pod 'KIF', :configurations => ['Debug']
    pod 'OCMock', :configurations => ['Debug']
end
