source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => 11.0
use_frameworks!

def shared_pods
  pod 'AWSS3', '~> 2.10'
end

target 'SimpleLogger' do
  shared_pods
end

target 'SimpleLoggerTests' do
  shared_pods
  pod 'KIF', :configurations => ['Debug']
  pod 'OCMock', :configurations => ['Debug']
end
